---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webui-auth
  namespace: ai
spec:
  encryptedData:
    password: AgBQ921t56DsFrl5C42ivp3+y9TGwT2m9HBr3RV79Di7oylph+zLiUytYPhWQ0lxBU98xSrJP/acdV+eBq7J+ssGm0IyrPFV/bPg2l7sphR9gMUAftUzLdQfwz4qmj+wo5jn6CF/+qGfiwDKd2x6fvqLA+16weeZqhup91ziWqH/pN0P9Xfnz/VAGetvTGLhhKZc6CHRAvcBqSAZNlvAqFNNCb5wAKH7oqDWo8BidPYlysNqngp1eK7aI6NVwuvklq7a1Q5mllvDPLr41siWAFw/KOfh0xwX1AyQan4LggoVQ8HW9h6p3izbnFCwWRIOa3NEsLDIiF7DwbXC99veeCUGSlT+tHEI47jR2zIOMw535mZ7OxPkRQjnOymlbX8rDWXYhbuJn1atk/o/Zqxg/Mvk/0r/zzwPjdwetY0nb+idDqPuuORNr18UcbMHvnC285PQx2I7fDRvgYw+8MBGMBbRNvK6Ef4vEaqxTSyHf38/LhaK1Au2ja5jvKDyGYKzebaAGCXKPFIX2bQ+Kmzdtt/Dag6StLRkMK5El+AnJnnknugeVt/7+llYYIBU8Km9a/jr4IXG93woWFbYlv1bcjFd7+bjOw9OuU/eDjgsd6o31Sgv1DUfxwHQGmXSFEaJciybqP933i7SwYtDn8SEHHwimavv3cqcdk8vyDzluqU7UUb1YNTyqcsEf9Az8PHDen8M2DpA5jEI
  template:
    metadata:
      name: webui-auth
      namespace: ai
